### ISSUE TITLE
How to enable the parameter -unrestricted?

### ISSUE THREAD

**Issue by silvioprog** [Embarcadero/paserver-docker#1]
Hi.

On Linux, mostly applications uses their configuration file inside the `/etc` repository, however, the `paserver-docker` container doesn't allow to access other path levels since its `-unrestricted` parameter is not enabled.

Is there any chance to enable this parameter?

Edit: The PAServer always remove all files inside the destination binary directory, this way, there is no any chance even symbolic links, since they will be removed each build at all.

Thank you!

**Comment by FMXExpress** [comment]
Create your own Dockerfile like so:

FROM radstudio/paserver
RUN apt-get update && apt-get install nano

And build it with whatever parameters you need:
docker build . -t paserver-child

Or just build the original Dockerfile yourself with the parameters you need.

**Comment by silvioprog** [comment]
Thank you!
