### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by giulianon** [Embarcadero/paserver-docker#11]
When I compile a simple console application I get the following error "Unable to create process: ''A' packet returned an error: 8'."
I've tried with docker installed in versions 18 and 22.

**Comment by jimmckeeth** [comment]
Are you able to test the connection from the IDE?

**Comment by giulianon** [comment]
Yes. In IDE the connection is ok. Only when compiling does it show this error.

**Comment by jimmckeeth** [comment]
You need to use `./run.sh` for debugging. The production version doesn't allow debugging.

**Comment by jimmckeeth** [comment]
Did that resolve the issue for you?

**Comment by giulianon** [comment]
Yes.  Thank you!
