### ISSUE TITLE
Exception EIdOSSLCouldNotLoadSSLLibrary 'Could not load SSL library.'

### ISSUE THREAD

**Issue by GitUserMarkus** [Embarcadero/paserver-docker#15]
Running a Linux64 Datasnap server compiled with Delphi 12 within this docker causes the before mentioned exception. Indy 10 as included in Delphi 12 seems to need package libcurl-openssl1.0-dev (or any other package that brings lib-opnessl1.0-dev) which I found no obvious way of how to install it within ubuntu:jammy.

Furthermore zlib1g-dev needs to be added to the imported packages.

**Comment by lmbelo** [comment]
@GitUserMarkus many of the Linux requirements seem to be missing. Please, refer to the following link to update your [Dockerfile](https://github.com/Embarcadero/paserver-docker/blob/f44e4e332fed71b054ab095b7ebf140272e3b882/Dockerfile#L10) while we fix it:

https://docwiki.embarcadero.com/RADStudio/Alexandria/en/Linux_Application_Development

**Comment by lmbelo** [comment]
@GitUserMarkus we have the missing libraries added to the new image and everything should work fine now.

You can reopen this issue if you face the same problem again.
