### ISSUE TITLE
When will it support RAD Studio 10.4?

### ISSUE THREAD

**Issue by StefanOlovJansson** [Embarcadero/paserver-docker#6]
I tried to pull the Docker image (radstudio/paserver) from Docker Hub. When I tried to use it the version of pa-server didn't seem to be compatible with RAD Studio 10.4. 

Is this a known problem or a new one? Is there going to be an updated version on Docker Hub?

NB. When I cloned this project from GitHub I could see folders for 10.3.2 and 10.3.3 but none for 10.4.

**Comment by FMXExpress** [comment]
I filed a ticket: https://quality.embarcadero.com/browse/RSP-30507

**Comment by StefanOlovJansson** [comment]
I have added a pdf file here that describes the problem with screenshots:

[When setting up a platform assistant profile in Delphi.pdf](https://github.com/Embarcadero/paserver-docker/files/5128247/When.setting.up.a.platform.assistant.profile.in.Delphi.pdf)

When can I expect a solution to this issue (since I need it for my work)? Alternatively if you have a work-around to suggest that would work for me?

**Comment by StefanOlovJansson** [comment]
I don't seem to have access yet to the view the ticket you filed...

**Comment by marcocantu** [comment]
We had some delays to create new installers for RAD Server and 10.4. They are now available on GetIt. Starting with those we'll update the docker images ASAP.

**Comment by StefanOlovJansson** [comment]
Will the Docker image also be updated on Docker Hub?

**Comment by marcocantu** [comment]
> Will the Docker image also be updated on Docker Hub?

That is the plan, but the link above is to a bug in the current installer so we need to fix it first

**Comment by StefanOlovJansson** [comment]
Do we need a separate JIRA case for Docker Hub?

**Comment by marcocantu** [comment]
No need, I'm tracking it separately

**Comment by StefanOlovJansson** [comment]
PS. I am just starting to use RAD Studio for targeting Linux, so I am a beginner when it comes to this. I have been asked to convert an application to a Linux Daemon (it is currently running as a Windows Service).

**Comment by StefanOlovJansson** [comment]
How is this going? Is there any work-around available for me to be able to proceed with my project? Any other Docker image I can use for this purpose?

**Comment by FMXExpress** [comment]
@StefanOlovJansson, if you have 10.3.3 available to you, you should use that for the docker image support until a 10.4 docker image can be made available. I don't think there were any big changes between 10.3.3 and 10.4 as far as RAD Server. Unless you specifically need something that was changed in FireDAC in 10.4.

**Comment by StefanOlovJansson** [comment]
Do you have any idea when such a Docker image will be made available?

**Comment by FMXExpress** [comment]
@StefanOlovJansson Updated now.
